project_id = "qrkvyvtarmsfwbmvjvzy"

[functions.generate-story-page]
verify_jwt = false

[functions.edit-story-image]
verify_jwt = false

[functions.generate-cover-page]
verify_jwt = false

[functions.edit-cover-image]
verify_jwt = false

[functions.translate-story-text]
verify_jwt = false

[functions.heygen-list-voices]
verify_jwt = false

[functions.heygen-list-avatars]
verify_jwt = false

[functions.heygen-generate-video]
verify_jwt = false
